### ISSUE TITLE
Parameter org-code should be case-sensitive

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/spine-directory-service-api#80] opened 2020-10-12 11:32 UTC
The query parameter org-code should be case-sensitive.

Endpoint - POST: https://int.api.service.nhs.uk/spine-directory/Endpoint
Query Parameter -  service-id: urn:nhs:names:services:pds:MCCI_IN010000UK13 and org-code - ygmyh
Headers - apikey: myG6cYQthVUzGeA0sHqCVPp3aSSZItF3

Currently, it is expecting org-code as Ygmyh, YgMYh, ygmyh

**Comment by michael-kainos** [comment] 2020-10-28 13:38
This needs more information of what the issue is here

**Comment by sonalnegivarma** [comment] 2020-11-02 11:56
Parameter org-code should be case-sensitive:

Description:
We are getting 401 unauthorized while sending the org-code value as non case-sensitive

curl --location --request GET 'https://int.api.service.nhs.uk/spine-directory/Endpoint?org-code=YgMYh&service-id=urn:nhs:names:services:pds:MCCI_IN010000UK13'

Component:
Spine directory service(SDS) adaptor

Version:
N/A

Step to Reproduce:

Test case: 
1) org-code should be case-sensitive

Preconditions:
URL - GET: https://int.api.service.nhs.uk/spine-directory/Endpoint
Query Parameter - org-code - Ygmyh or YgMYh or ygmyh
service-id - urn:nhs:names:services:pds:MCCI_IN010000UK13
apikey - myG6cYQthVUzGeA0sHqCVPp3aSSZItF3


Environment
Integration environment

Severity
Low,

Priority
Not urgent

Expected Behavior:

The response would be either 400 bad request or 404 not found

Actual Behavior:

We are getting 401 Unauthorized

**Comment by michael-kainos** [comment] 2020-11-04 09:31
@sonalnegivarma the org-code is static. This is provided in uppercase format and should not be changed. We can close this.

**Closed by michael-kainos** 2020-11-04 09:31 UTC
